import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Container, Flex, Box, Heading, Text, IconButton, Button, VStack, HStack, Wrap, WrapItem, FormControl, FormLabel, Input, InputGroup, InputLeftElement, Textarea, } from '@chakra-ui/react';
import { MdPhone, MdEmail, MdLocationOn, MdFacebook, MdOutlineEmail, } from 'react-icons/md';
import { BsGithub, BsDiscord, BsPerson } from 'react-icons/bs';
export default function ContactPage() {
    return (_jsx(Container, { bg: "#ededee", maxW: "full", mt: 0, centerContent: true, overflow: "hidden", children: _jsx(Flex, { children: _jsx(Box, { bg: "#02054B", color: "white", borderRadius: "lg", m: { sm: 4, md: 16, lg: 10 }, p: { sm: 5, md: 5, lg: 16 }, children: _jsx(Box, { p: 4, children: _jsxs(Wrap, { spacing: { base: 20, sm: 3, md: 5, lg: 20 }, children: [_jsx(WrapItem, { children: _jsxs(Box, { children: [_jsx(Heading, { children: "Contact" }), _jsx(Text, { mt: { sm: 3, md: 3, lg: 5 }, color: "gray.500", children: "Fill up the form below to contact" }), _jsx(Box, { py: { base: 5, sm: 5, md: 8, lg: 10 }, children: _jsxs(VStack, { pl: 0, spacing: 3, alignItems: "flex-start", children: [_jsx(Button, { size: "md", height: "48px", width: "200px", variant: "ghost", color: "#DCE2FF", _hover: { border: '2px solid #1C6FEB' }, leftIcon: _jsx(MdPhone, { color: "#1970F1", size: "20px" }), children: "+91-988888888" }), _jsx(Button, { size: "md", height: "48px", width: "200px", variant: "ghost", color: "#DCE2FF", _hover: { border: '2px solid #1C6FEB' }, leftIcon: _jsx(MdEmail, { color: "#1970F1", size: "20px" }), children: "hello@abc.com" }), _jsx(Button, { size: "md", height: "48px", width: "200px", variant: "ghost", color: "#DCE2FF", _hover: { border: '2px solid #1C6FEB' }, leftIcon: _jsx(MdLocationOn, { color: "#1970F1", size: "20px" }), children: "Karnavati, India" })] }) }), _jsxs(HStack, { mt: { lg: 10, md: 10 }, spacing: 5, px: 5, alignItems: "flex-start", children: [_jsx(IconButton, { "aria-label": "facebook", variant: "ghost", size: "lg", isRound: true, _hover: { bg: '#0D74FF' }, icon: _jsx(MdFacebook, { size: "28px" }) }), _jsx(IconButton, { "aria-label": "github", variant: "ghost", size: "lg", isRound: true, _hover: { bg: '#0D74FF' }, icon: _jsx(BsGithub, { size: "28px" }) }), _jsx(IconButton, { "aria-label": "discord", variant: "ghost", size: "lg", isRound: true, _hover: { bg: '#0D74FF' }, icon: _jsx(BsDiscord, { size: "28px" }) })] })] }) }), _jsx(WrapItem, { children: _jsx(Box, { bg: "white", borderRadius: "lg", children: _jsx(Box, { m: 8, color: "#0B0E3F", children: _jsxs(VStack, { spacing: 5, children: [_jsxs(FormControl, { id: "name", children: [_jsx(FormLabel, { children: "Your Name" }), _jsxs(InputGroup, { borderColor: "#E0E1E7", children: [_jsx(InputLeftElement, { pointerEvents: "none", children: _jsx(BsPerson, { color: "gray.800" }) }), _jsx(Input, { type: "text", size: "md" })] })] }), _jsxs(FormControl, { id: "name", children: [_jsx(FormLabel, { children: "Mail" }), _jsxs(InputGroup, { borderColor: "#E0E1E7", children: [_jsx(InputLeftElement, { pointerEvents: "none", children: _jsx(MdOutlineEmail, { color: "gray.800" }) }), _jsx(Input, { type: "text", size: "md" })] })] }), _jsxs(FormControl, { id: "name", children: [_jsx(FormLabel, { children: "Message" }), _jsx(Textarea, { borderColor: "gray.300", _hover: {
                                                                borderRadius: 'gray.300',
                                                            }, placeholder: "message" })] }), _jsx(FormControl, { id: "name", float: "right", children: _jsx(Button, { variant: "solid", bg: "#0D74FF", color: "white", _hover: {}, children: "Send Message" }) })] }) }) }) })] }) }) }) }) }));
}
